CREATE TABLE IF NOT EXISTS "team" (
  "id" INTEGER NOT NULL UNIQUE,
  "name" TEXT NOT NULL DEFAULT '',
  "slots" TEXT NOT NULL DEFAULT '[]',
  "trainer" TEXT NOT NULL,
  "notes" TEXT NOT NULL DEFAULT '',
  PRIMARY KEY ("id" AUTOINCREMENT)
);
